import type { Metadata } from "next";
import {
  Roboto_Flex as Roboto,
  Poppins,
} from 'next/font/google'
import "./globals.css";

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'], variable: '--font-roboto' })
const poppins = Poppins({ subsets: ['latin'], weight: ['400', '700'], variable: '--font-poppins' })

export const metadata: Metadata = {
  title: "cruel doubt",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${roboto.variable} ${poppins.variable} font-roboto bg-gray-50`}>{children}</body>
    </html >
  );
}
